version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
      - image: trufflesuite/ganache-cli

    working_directory: ~/token

    steps:
      - checkout

      - setup_remote_docker:   # (2)
          docker_layer_caching: true

      - run:
          name: Install Truffle
          command: |
            sudo npm install -g truffle

      - run:
          name: Run Ganache-Client
          command: |
            docker run --name ganache -d -p 8545:8545 trufflesuite/ganache-cli -a 30 -e 500

      - run:
          name: Run Test
          command: |
            truffle test
