version: 2

jobs:
  build:
    docker:
      - image: trufflesuite/ganache-cli:latest
    steps:
      - checkout

      # run test
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: |
          docker run --name ganache -d -p 8545:8545 trufflesuite/ganache-cli -a 30 -e 500
