version: 1

machine:
  node:
    version: 9.11.0
  services:
    - docker

jobs:
  build:
    docker:
      - image: trufflesuite/ganache-cli:latest
    steps:
      - checkout

      # run test
      - run:
          command:
            npm test
