version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
      - image: trufflesuite/ganache-cli -a 50 -e 500

    working_directory: ~/token

    steps:
      - checkout

      - setup_remote_docker:   # (2)
          docker_layer_caching: true

      - run:
          name: Install Truffle
          command: |
            sudo npm install -E zeppelin-solidity
            sudo npm install -g truffle

      - run:
          name: Run Test
          command: |
            truffle test
