version: 1
jobs:
  build:
    docker:
      - image: trufflesuite/ganache-cli:latest
    steps:
      - checkout

      # run test
      - run:
          command: |
            mkdir -p ${TEST_REPORTS}
            truffle test
            cp test-results.xml ${TEST_REPORTS}

      - store_artifacts:
          path: test-results.xml

      - store_test_results:
          path: /tmp/test-reports
