version: 1

jobs:
  build:
    docker:
      - image: trufflesuite/ganache-cli:latest
    steps:
      - checkout

      # run test
      - run: |
        docker run --name ganache -d -p 8545:8545 trufflesuite/ganache-cli -a 30 -e 500
